/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import javax.swing.JOptionPane;

import model.Arquivo;

public class JanelaCadastroVenda extends javax.swing.JFrame {

    /**
     * Creates new form JanelaCadastroVenda
     */
    public JanelaCadastroVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Arquivo arq = new Arquivo();
        int tam1 = arq.contarArquivos(".\\src\\model\\produtos\\categorias\\roupas\\roupasCadastradas");
        int tam2 =  arq.contarArquivos(".\\src\\model\\produtos\\categorias\\equipamentos\\equipamentosCadastrados");
        int tam3 = arq.contarArquivos(".\\src\\model\\produtos\\categorias\\calcados\\calcadosCadastrados");
        String texto;
        String[] vetGeral = new String[tam1+tam2+tam3];
        String[] inf;
        String conteudo;
        int i = 0;


        String[] nomesArq = arq.mostrarAqrquivos(".\\src\\model\\produtos\\categorias\\roupas\\roupasCadastradas");
        while(i<tam1){
            conteudo = arq.Read(".\\src\\model\\produtos\\categorias\\roupas\\roupasCadastradas\\" + nomesArq[i]);
            inf = conteudo.split("\n");
            texto = inf[0] + ";" + inf[1] + ";" + inf[5] + ";" + "Roupa";
            vetGeral[i] = texto;      
            i++;
        }

        int j = 0;
        nomesArq = arq.mostrarAqrquivos(".\\src\\model\\produtos\\categorias\\equipamentos\\equipamentosCadastrados");
        while(j < tam2){
            conteudo = arq.Read(".\\src\\model\\produtos\\categorias\\equipamentos\\equipamentosCadastrados\\" + nomesArq[j]);
            inf = conteudo.split("\n");
            texto = inf[0] + ";" + inf[1] + ";" + inf[4] + ";" + "Equipamento";
            vetGeral[i] = texto;  
            i++;
            j++;
        }
        
        int k = 0;
        nomesArq = arq.mostrarAqrquivos(".\\src\\model\\produtos\\categorias\\calcados\\calcadosCadastrados");
        while(k < tam3){
            conteudo = arq.Read(".\\src\\model\\produtos\\categorias\\calcados\\calcadosCadastrados\\" + nomesArq[k]);
            inf = conteudo.split("\n");
            texto = inf[0] + ";" + inf[1] + ";" + inf[4] + ";" + "Calcado";
            vetGeral[i] = texto;
            i++;
            k++;
        }

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("COMPRA");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = vetGeral;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jList1FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CLIENTE");

        jLabel3.setText("CPF");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("COMPRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade");

        jButton2.setText("Voltar");
        jButton2.setActionCommand("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(193, 193, 193)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1FocusGained

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    int id = 1;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cpf = jTextField1.getText();
        String nome = "";
        String caminho = ".\\src\\model\\clientes\\clientesCadastrados";
        String[] inf;
        String conteudo;
        Arquivo arq = new Arquivo();
        int tam = arq.contarArquivos(caminho);
        String[] nomesArquivos = arq.mostrarAqrquivos(caminho);
        for(int i = 0; i<tam; i++){
            conteudo = arq.Read(caminho + "\\" + nomesArquivos[i]);
            inf = conteudo.split("\n");
            if(cpf.equals(inf[1])){
               nome = inf[0]; 
            }
        }

        String getProduto = (String) jList1.getSelectedValue();
        String[] produto = getProduto.split(";");

        int quant = (int) jSpinner1.getValue();

        if(quant == 0){
            JOptionPane.showMessageDialog(null, "Informe uma quantidade!");
        }
        else if(Integer.parseInt(produto[2]) >= quant){
            String texto = nome + ";" + cpf + ";"+ produto[0] + ";" + produto[1] + ";" + produto[2];
            
            arq.Write(".\\src\\model\\vendas\\Venda" + id + ".txt", texto);
            id++;
    
            String caminhoRoupa = ".\\src\\model\\produtos\\categorias\\roupas\\roupasCadastradas";
            String caminhoEquip = ".\\src\\model\\produtos\\categorias\\equipamentos\\equipamentosCadastrados";
            String caminhoCalca = ".\\src\\model\\produtos\\categorias\\calcados\\calcadosCadastrados";
            int tam1 = arq.contarArquivos(caminhoRoupa);
            int tam2 = arq.contarArquivos(caminhoEquip);
            int tam3 = arq.contarArquivos(caminhoCalca);
    
            String[] vet;
            String newConteudo;
            int quantidade = (int) jSpinner1.getValue();
            int diferenca;
    
            String[] nomesArq = arq.mostrarAqrquivos(caminhoRoupa);
            

            if(produto[3].equals("Roupa")){

                vet = new String[tam1];
                for(int i = 0; i<tam1; i++){
                    conteudo = arq.Read(caminhoRoupa + "\\" + nomesArq[i]);
                    vet = conteudo.split("\n");
                    if(produto[0].equals(vet[0])){
                        diferenca = Integer.parseInt(vet[5]) - quantidade;
                        vet[5] = "" + diferenca;
                        newConteudo = vet[0] + "\n" + vet[1] + "\n" + vet[2] + "\n" + vet[3] + "\n" + vet[4] + "\n" + vet[5];
                        arq.Write(caminhoRoupa + "\\" + nomesArq[i], newConteudo);
                    }
                    
                }
            } 
            
            else if(produto[3].equals("Equipamento")){
                nomesArq = arq.mostrarAqrquivos(caminhoEquip);
                vet = new String[tam2];
                for(int i = 0; i<tam2; i++){
                    conteudo = arq.Read(caminhoEquip + "\\" + nomesArq[i]);
                    vet = conteudo.split("\n");
                    if(produto[0].equals(vet[0])){
                        diferenca = Integer.parseInt(vet[4]) - quantidade;
                        vet[4] = "" + diferenca;
                        newConteudo = vet[0] + "\n" + vet[1] + "\n" + vet[2] + "\n" + vet[3] + "\n" + vet[4];
                        arq.Write(caminhoEquip + "\\" + nomesArq[i], newConteudo);
                    }
                }
            } 
            
            else if(produto[3].equals("Calcado")){
                nomesArq = arq.mostrarAqrquivos(caminhoCalca);
                vet = new String[tam3];
                for(int i = 0; i<tam3; i++){
                    conteudo = arq.Read(caminhoCalca + "\\" + nomesArq[i]);
                    vet = conteudo.split("\n");
                    if(produto[0].equals(vet[0])){
                        diferenca = Integer.parseInt(vet[4]) - quantidade;
                        vet[4] = "" + diferenca;
                        newConteudo = vet[0] + "\n" + vet[1] + "\n" + vet[2] + "\n" + vet[3] + "\n" + vet[4] + "\n" + vet[5];
                        arq.Write(caminhoCalca + "\\" + nomesArq[i], newConteudo);
                    }
                }
            }
            JOptionPane.showMessageDialog(null, "Compra Realizada!");

        }

        else{
            JOptionPane.showMessageDialog(null, "Quantidade indisponivel!");
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new JanelaPrincipal().setVisible(true);
        new JanelaPrincipal().dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadastroVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
